image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start Appsmith
    init: |
      docker-compose build # Build Docker images
    command: |
      docker-compose up # Start the Appsmith service

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker # Docker extension for VS Code
