version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: appsmith-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0"]

  appsmith:
    image: appsmith/appsmith-ce:latest
    container_name: appsmith
    ports:
      - "80:80"
    environment:
      APPSMITH_REDIS_URL: redis://redis:6379
      APPSMITH_MONGODB_URI: mongodb://appsmith-mongo:27017/appsmith?replicaSet=rs0
      APPSMITH_ENCRYPTION: 6z3TALG):x}=30P
    depends_on:
      - redis
      - mongo

volumes:
  mongo-data:
